### ISSUE TITLE
$this->plugin $plugin;

### ISSUE THREAD

**Issue by indexacm** [ByEvidencias/EasyGamemode#1]
Quita esa mierda da sida

**Comment by ByEvidencias** [comment]
Silencio peter, cuando suba el próximo plugin, hago una versión mejorada de los otros

**Comment by indexacm** [comment]
Gracias por escuchar, pero ahora tengo que asistir a un médico para que me cure la sida que me acaba de proporcionar tu $this-> plugin = $plugin 

Gracias.
